sudo: required

services:
    - docker

before_install:
    - docker build -t shoaib-mdr/dockerreact -f Dockerfile.dev .

scripts:
    - docker run shoaib-mdr/dockerreact npm run test -- --coverage --watchAll=false

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "DockerReact"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-1-680280243443"
    bucket_path: "DockerReact"
    on:
        branch: master



