sudo: required

services:
    - docker
    
before_install:
    - docker build -t Shoaib-mdr/DockerReact -f Dockerfile.dev .

scripts:
    - docker run Shoaib-mdr/DockerReact npm run test -- --coverage


